[buildPlans.IosevkaRo]
family = "Iosevka Ro"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.IosevkaRo.variants.design]
capital-g = "toothless-corner-serifless-hooked"
capital-i = "serifed"
capital-j = "serifed-symmetric"
capital-q = "crossing-baseline"
capital-r = "straight-open-serifless"
capital-s = "serifless"
capital-w = "straight-serifless"
a = "double-storey-toothless-rounded"
b = "toothless-corner-serifless"
g = "single-storey-earless-corner"
i = "hooky"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "bent-hook"
u = "toothless-corner-serifless"
cyrl-a = "double-storey-hook-inward-serifed-toothless-rounded"
asterisk = "hex-high"
paren = "normal"
brace = "straight"
guillemet = "straight"
at = "compact"
dollar = "open"
partial-derivative = "straight-bar"
micro-sign = "toothless-corner-serifless"
lig-double-arrow-bar = "without-notch"

[buildPlans.IosevkaRo.widths.Normal]
shape = 600
menu = 5
css = "normal"
