name: PR Font Build Validation

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Font
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install ttf-auto-hint
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint

      - name: Build Font
        shell: bash
        run: |
          npm install
          npm run build -- ttf::IosevkaRo

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: font
          path: dist/
